type Topic={slug:string;title:string;excerpt:string;service:string;href:string;scenario:string;artifact:string;owner:string;risk:string;example:string};
const image='/images/thumbnail-backgrounds/talent-map.webp';
const sources=[
 {name:'Philippine National Privacy Commission: Data Privacy Act resources',url:'https://privacy.gov.ph/data-privacy-act/',note:'Primary Philippine guidance on personal-information processing and accountability.'},
 {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework',note:'A voluntary framework for identifying and managing privacy risk.'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Risk-management guidance relevant to governance, access, records, and recovery.'},
 {name:'CISA: More than a Password',url:'https://www.cisa.gov/secure-our-world/use-strong-passwords',note:'Current first-party guidance on account protection and multifactor authentication.'}
];
const topics:Topic[]=[
 ['philippines-training-needs-matrix','Build a training needs matrix for a Philippines offshore team','Map recurring tasks to required knowledge, practice evidence, review ownership, and a safe next assignment.','training administration','/services/training-administration','A new coordinator finished general induction but still needs supervised practice on refunds, account changes, and exception notes.','a matrix linking every task to prerequisites, a controlled exercise, an accepted example, reviewer, status, and reassessment date','The process owner decides whether evidence is sufficient for live work and broader access.','using course attendance as proof of task readiness','For refund support, the learner classifies fictional cases, cites the rule, drafts the note, and stops at approval.'],
 ['offshore-training-completion-evidence','What counts as training completion for an offshore support role?','Replace attendance-only records with task evidence, reviewer acceptance, exception practice, and a readiness decision.','training administration','/services/training-administration','A team member watched six sessions but cannot identify when a real request needs manager review.','a completion record with objective, version, practice task, exception, reviewer observation, correction, and remaining limits','A qualified subject owner decides readiness for live work.','equating time spent with competence','A scheduling learner handles an ordinary booking, a time-zone conflict, and an out-of-policy request.'],
 ['offshore-performance-report-metric-dictionary','Create a metric dictionary for offshore performance reporting','Define every measure, source, cut-off, exclusion, owner, and limitation before a dashboard shapes decisions.','performance reporting','/services/performance-reporting','Two reports show different completion rates because one excludes returned items and the other rolls unfinished work forward.','a metric dictionary with purpose, formula, source fields, inclusion rules, cut-off, owner, limitations, and history','Managers approve definitions, targets, and conclusions about performance.','publishing precision without exposing exclusions or source changes','For accepted-work rate, define corrected items, acceptance authority, and work waiting for manager approval.'],
 ['philippines-performance-report-correction-workflow','Design a correction workflow for Philippines performance reports','Trace reported errors from challenge to source review, approval, republication, and notice.','performance reporting','/services/performance-reporting','Approved leave was counted as missed coverage; a silent dashboard edit would erase why the number changed.','a correction log with challenged figure, version, evidence, impact, owner, replacement, recipients, and closure time','The metric owner approves revisions and handles workforce consequences.','overwriting reports or treating disagreement as a data error','Trace the exception to an old schedule export, preserve the original, and list every downstream summary.'],
 ['philippines-schedule-coverage-constraint-register','Keep a coverage constraint register for a Philippines offshore schedule','Plan from approved availability, dependencies, review windows, and exceptions without turning assumptions into promises.','schedule coordination','/services/schedule-coordination','A calendar looks covered, but the only escalation owner is absent during the final two hours.','a register listing need, availability, time zone, overlap, dependency, backup, conflict, owner, and effective date','Managers approve hours, overtime, leave, and service promises.','filling gaps with unapproved assumptions','Separate routine end-of-day responses from refund approval and expose the uncovered decision window.'],
 ['offshore-schedule-change-confirmation','Confirm offshore schedule changes without losing the source of truth','Use one controlled record so revised hours, coverage, approvals, and commitments stay aligned.','schedule coordination','/services/schedule-coordination','A swap is agreed in chat while the roster, payroll input, meeting calendar, and coverage board keep the old hours.','a change record with request, old and new coverage, approvals, systems, notifications, and verifier','Managers approve overtime, leave, contractual changes, and service-risk exceptions.','treating a chat reaction as approval','Check interview coverage and reporting cut-offs before publishing one approved shift swap.'],
 ['philippines-people-operations-case-intake-boundary','Set case-intake boundaries for Philippines people operations support','Organise employee requests while sensitive judgment, investigation, policy interpretation, and outcomes stay with authorised owners.','people operations support','/services/people-operations-support','An employee asks a coordinator whether a manager comment breaches policy. Logging is administrative; interpreting is not.','an intake record with category, minimum facts, confidentiality, acknowledgement, owner, urgency, access, and next action','HR handles advice, investigations, findings, accommodations, and employment decisions.','collecting excess detail or sounding like a policy decision','Route a payroll-document request routinely while an allegation goes directly to the named senior owner.'],
 ['offshore-personnel-record-correction-request','Handle personnel record correction requests in an offshore support lane','Separate intake and evidence gathering from approval so records change without silent edits or excess access.','people operations support','/services/people-operations-support','An employee reports a wrong contact and job title; only one field is authorised for self-service.','a request showing field, old and proposed value, evidence, authority, systems, approval, checks, and notice','Authorised owners decide disputed facts, sensitive changes, and policy exceptions.','editing from an informal message without checking identity or downstream impact','Route the title for approval and process the contact through the approved identity check.'],
 ['philippines-compliance-document-expiry-register','Build a compliance document expiry register for Philippines support','Track owners, validity dates, renewal evidence, access limits, and escalation without transferring compliance judgment.','compliance document administration','/services/compliance-document-administration','A vendor certificate expires next month, but a tracker shows no owner, requirement, or safe holding action.','a register with type, owner, location, validity basis, lead time, action, evidence, access class, and escalation date','Compliance, legal, security, or business owners interpret requirements and exceptions.','treating a reminder as proof of compliance','Flag the certificate, confirm the contract owner, link the restricted source, and record the response.'],
 ['offshore-audit-evidence-request-queue','Run an audit evidence request queue with offshore administrative support','Make evidence requests owned and traceable while qualified owners retain interpretation, approval, and disclosure.','compliance document administration','/services/compliance-document-administration','An auditor requests quarterly access evidence; only the control owner can confirm scope and approve release.','a queue with requester, scope, due date, owner, source, period, version, sensitivity, reviewer, delivery, and questions','Control owners validate meaning and authorised owners approve sensitive disclosure.','sending convenient evidence that is stale, incomplete, or unauthorised','Record the population and period, obtain the export, link exceptions, and wait for approval.'],
 ['philippines-retention-pulse-survey-administration','Administer a retention pulse survey with a Philippines support team','Coordinate a small survey with clear purpose, privacy boundaries, response handling, and manager-owned action.','retention program support','/services/retention-program-support','A manager wants named morale comments without first defining purpose or confidentiality.','a plan with purpose, audience, questions, window, identity setting, access, threshold, escalation, report, and owner','Leaders decide design, confidentiality promises, interpretation, and interventions.','collecting identifiable sensitive comments without justified purpose','Report only sufficiently aggregated results and provide a separate named support channel.'],
 ['offshore-stay-interview-follow-up-tracker','Create a follow-up tracker for offshore stay interviews','Turn manager-owned conversations into explicit actions, realistic commitments, protected records, and timely follow-up.','retention program support','/services/retention-program-support','A manager promises a workload review, but the action disappears into private notes.','a tracker with consented summary, owner, date, dependency, confidentiality, status, next conversation, and closure','Managers conduct conversations, interpret concerns, make commitments, and handle sensitive matters.','turning confidential notes into a broad performance record','Track the workload review openly while sensitive context remains in the restricted HR record.']
].map(([slug,title,excerpt,service,href,scenario,artifact,owner,risk,example])=>({slug,title,excerpt,service,href,scenario,artifact,owner,risk,example} as Topic));
function sections(t:Topic){return [
{heading:'Frame the decision',paragraphs:[`${t.scenario} The operating question belongs to ${t.service}: what evidence lets an accountable manager make the next decision safely? Name the decision, source, consequence, and owner before choosing software. Broad directions such as keep it updated do not define completeness, a stop point, or a trustworthy handoff.`,`Start with a recent example and trace request, source, action, review, and finish. Write down uncertainty rather than smoothing it into a confident status. This separates a genuine staffing need from a collection of frustrations and gives the offshore role an observable purpose.`]},
{heading:'Build an inspectable record',paragraphs:[`Use ${t.artifact}. Each status needs evidence, an owner, and a next action. Link to the approved source instead of copying sensitive detail into chat. Mark missing or disputed inputs honestly. Another authorised person should be able to resume the work without reconstructing private messages.`,`Keep fields small and testable. Record the effective date, procedure version, accepted example, and person who acknowledged a consequential handoff. A colourful dashboard cannot compensate for an undefined denominator, a missing approval, or a value copied from a stale export.`]},
{heading:'Set authority and privacy boundaries',paragraphs:[`${t.owner} The specialist may gather evidence, organise records, prepare options, and request a decision. Put the boundary beside the procedure and repeat it in escalation examples. Silence is not approval, even when a queue is ageing.`,`Collect only information needed for the approved purpose. Candidate and workforce records may include identity, contact, schedule, performance, or employment information. Apply company retention and response rules, Philippine privacy guidance, and every other jurisdictional, contractual, and sector duty that applies.`]},
{heading:'Test routine and exception cases',paragraphs:[`${t.example} Use fictional or appropriately controlled data until handling and permissions are approved. The test must create an observable record and require the contributor to use a stop condition, not merely repeat the instruction.`,`Add a missing input, conflicting source, and urgent request. Watch whether the contributor invents a value or names the exact decision owner and safe holding action. Repeated questions often reveal weak examples or inconsistent reviewers, so repair the workflow before increasing volume.`]},
{heading:'Grant access from the task outward',paragraphs:[`Start with the smallest account and data view that supports the approved step. Use separate identities, role-based permissions, multifactor authentication, and a named removal owner. Test an intended and prohibited action so the check proves more than a successful login.`,`The failure to prevent is ${t.risk}. Document prohibited exports, bulk actions, approvals, and external messages. Broader access needs a specific purpose, approval, and review date. Remove permissions promptly when the task, assignment, or person changes.`]},
{heading:'Measure quality without shortcuts',paragraphs:[`Pair throughput with acceptance evidence. Review ordinary work, corrected work, overdue handoffs, unresolved exceptions, and manager waiting time. A high count can hide easy items, skipped checks, or a manager privately repairing difficult work.`,`Use return reasons that improve the system: wrong source, stale version, unsupported inference, incomplete handoff, access issue, or unclear standard. When reviewers disagree, preserve the disputed field and let the standard owner settle it before grading the contributor.`]},
{heading:'Design the handoff and escalation',paragraphs:[`A complete handoff states what arrived, what was checked, what changed, what remains open, who acts next, and when delay changes a commitment. Sending a message is not the same as transferring responsibility; consequential work needs acknowledgement.`,`Create escalation levels for routine missing inputs, conflicting evidence or commitments at risk, and privacy, security, legal, financial, safety, or policy concerns. Give each level an owner, backup, response expectation, channel, and safe holding action.`]},
{heading:'Pilot and choose the next step',paragraphs:[`Run a bounded volume with a written review date. Choose expand, continue, narrow, repair, or stop, then record the evidence and next owner. More volume, a second task, or wider access each needs its own acceptance test; stable work does not create silent permission.`,`If the workflow matches a real need, review Offshore Resourcing's ${t.service} service. Prepare systems, hours, sample records, approval boundaries, and manager availability for a role-planning conversation. Start with the first repeatable task and the decision that stays with your team.`]}
];}
export const dailyBlogSep18Offa60Posts=topics.map((t,i)=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10+i%2,publishedAt:'2026-09-18',image,details:{sections:sections(t),sources,service:t.service,serviceHref:t.href,faqs:[{q:'What does the manager own?',a:t.owner},{q:'What should the specialist prepare?',a:`The specialist can prepare ${t.artifact}.`}]}}));
export const dailyBlogSep18Offa60Details=Object.fromEntries(dailyBlogSep18Offa60Posts.map(p=>[p.slug,p.details]));
