type Topic={slug:string;title:string;excerpt:string;problem:string;record:string;boundary:string;trial:string};
const image='/images/thumbnail-backgrounds/document-workflow.webp';
const topics:Topic[]=[
['offshore-content-brief-readiness-score','Score a content brief before it enters the offshore writing queue','A brief readiness score exposes missing decisions before a writer spends time filling gaps.','whether the brief has enough context to support a responsible first draft','a five-part check covering reader question, intended action, approved sources, exclusions, and accountable reviewer','A score can flag missing inputs, but it cannot approve a weak premise or replace editorial judgment.','Score the next eight briefs, then compare low-scoring briefs with clarification requests and returned drafts.'],
['philippines-content-specialist-daily-startup-checklist','A daily startup checklist for a Philippines-based content specialist','A ten-minute startup check turns a list of assignments into an ordered, workable day.','which item is truly ready, time-sensitive, and within the specialist\'s authority','a dated queue view showing priority, source access, due time, dependency, and first handoff','The checklist should organize approved work. It must not let the specialist invent priorities or bypass a blocked source.','Run it for one week and record which checks changed the order of work.'],
['offshore-article-evidence-receipt','Attach an evidence receipt to every offshore article draft','A compact evidence receipt helps an editor trace important claims without reopening the entire research trail.','which claims require verification and where their support can be found','a claim table with source owner, publication date, relevant section, access date, and any qualification','A link is not proof by itself. The writer must not present an inference as a sourced fact.','Test receipts on one service guide and one research-heavy article, then time the fact-check.'],
['content-queue-aging-alerts','Use queue-aging alerts without turning them into deadline theatre','Age alerts should uncover waiting and ownership problems, not pressure writers to release unfinished work.','when an item has waited long enough to require a decision from its owner','a timestamped status with current owner, waiting reason, next decision, and agreed response time','Elapsed time never overrides factual review, approval, access controls, or a declared stop condition.','Review every item older than its stage threshold for five days and classify the actual source of delay.'],
['offshore-editorial-return-reason-codes','Give returned drafts useful reason codes','A small set of return reasons shows where briefs, evidence, and review instructions are failing repeatedly.','why a draft cannot advance and what must change before it returns','one primary reason, an explanatory note tied to exact text, a revision owner, and a recheck requirement','Reason codes must diagnose the work, not rank people or replace a clear review comment.','Tag twenty returns, merge ambiguous categories, and inspect whether the code led to the right correction.'],
['daily-publishing-cutoff-exception-rule','Write the exception rule before the daily publishing cutoff','A pre-agreed exception rule keeps late work from slipping past checks merely to protect a daily count.','which late changes can wait, which need a narrow recheck, and which stop publication','a cutoff log naming the change, affected gate, decision owner, disposition, and next review time','Only an authorised publisher can accept a release exception, and mandatory factual and technical checks still apply.','Apply the rule to three simulated late changes before using it on a live release.'],
['philippines-research-assistant-source-escalation','Teach a Philippines-based research assistant when to escalate a source problem','A source escalation ladder helps researchers stop cleanly when evidence is missing, conflicting, or too old.','whether the researcher can resolve the gap within the approved source policy','a short escalation note that states the claim, attempted sources, conflict, consequence, and requested decision','The researcher may compare and document sources but cannot settle a policy, legal, or commercial claim by assumption.','Seed a practice brief with one dead link, one contradiction, and one outdated figure, then review the escalations.'],
['offshore-content-calendar-dependency-map','Add dependencies to the offshore content calendar','A dependency map makes approvals, source refreshes, design inputs, and release windows visible beside due dates.','what must happen before an article can move and who owns that prerequisite','a calendar entry linking each dependency to its owner, required date, status, and fallback','The map should reveal constraints. It must not create a false promise that an uncertain dependency will arrive on time.','Map dependencies for the next ten articles and compare predicted waits with actual waits.'],
['editorial-rubric-change-log','Keep a change log for the editorial rubric','When review criteria change, a dated log prevents writers and editors from working from different versions.','which rule applies to a draft and whether older work needs a targeted recheck','a version note with changed criterion, reason, approver, effective date, examples, and transition rule','A rubric log records approved standards. Contributors should not rewrite criteria to excuse a missed requirement.','Introduce one minor rubric change and check whether every active owner can identify the applicable version.'],
['offshore-article-correction-owner','Name the correction owner before an article goes live','A named correction owner shortens the path from a reported problem to a verified fix.','who investigates, who approves the correction, and who confirms production after release','a correction card with route, report time, issue type, evidence, accountable decision maker, and verification step','The operational owner can coordinate the response but cannot quietly alter sensitive claims or erase the correction record.','Run a tabletop exercise with a broken image and a disputed factual statement.'],
['content-handoff-overlap-agenda','Use overlap time for decisions, not status recitals','A short overlap agenda reserves scarce shared hours for blocked choices that asynchronous notes could not settle.','which questions genuinely need simultaneous discussion across time zones','an agenda listing the decision, context link, options, owner, and deadline, followed by a dated outcome','Routine progress belongs in the queue record. A meeting should not become an undocumented approval channel.','Measure decision yield across five overlap sessions and remove agenda items that could have been resolved asynchronously.'],
['daily-article-routine-control-review','Review the controls in a daily article routine once a month','A monthly control review removes stale checks and strengthens the few gates that protect real publishing risks.','which controls catch meaningful problems and which have become unused ceremony','a control register with purpose, owner, evidence, exceptions, last failure caught, and next review date','The review cannot weaken legal, security, factual, or publication requirements merely because they take time.','Inspect one month of exceptions and corrections, then change only one control at a time.']
].map(([slug,title,excerpt,problem,record,boundary,trial])=>({slug,title,excerpt,problem,record,boundary,trial})) as Topic[];
const make=(t:Topic)=>({sections:[
{heading:'Name the operating question',paragraphs:[`Published September 10, 2026. Start with ${t.problem}. Put that question in the working brief so the contributor knows what the routine is meant to protect.`,`${t.excerpt} It is useful only when another owner can inspect the result and act on it.`]},
{heading:'Create a small, verifiable record',paragraphs:[`Use ${t.record}. Keep the record beside the article or queue item, with links to approved source material rather than copies of restricted information.`,`Separate observed facts from recommendations and open questions. That distinction matters when work moves between a Philippines-based contributor and a manager in another time zone.`]},
{heading:'Set the authority boundary',paragraphs:[t.boundary,`Write down the stop condition before the deadline arrives. A contributor should be able to pause and escalate without being treated as the final decision maker.`]},
{heading:'Place it at the point of risk',paragraphs:[`Run the check immediately before the handoff or decision it protects. Record the outcome once, then reuse that evidence downstream instead of asking each person to reconstruct it.`,`If one input changes, reopen the affected check. Keep the rest of the verified work intact unless the change has wider consequences.`]},
{heading:'Pilot it with ordinary and awkward work',paragraphs:[t.trial,`Include a normal item and an exception. Track waits, rework, missed evidence, and overrides, but do not reward speed when the acceptance standard was not met.`]},
{heading:'Decide whether the routine earns its place',paragraphs:[`Review the pilot with the people who create and receive the handoff. Keep the routine if it makes ownership or evidence clearer; revise or remove fields that nobody uses.`,`Give every retained control an owner and review date. A daily article system stays healthy through specific corrections, not through a growing pile of checklists.`]}
],faqs:[{q:'Who should own this routine?',a:'The content manager owns the standard, the contributor records the work performed, and the authorised publisher retains the release decision.'},{q:'What evidence should the pilot preserve?',a:'Keep dates, owners, waiting reasons, returned work, exceptions, and the final decision so the team can review what actually happened.'}]});
export const dailyBlogSep10Posts=topics.map((t,i)=>({...t,minutes:8+i%3,publishedAt:'2026-09-10' as const,image,details:make(t)}));
export const dailyBlogSep10Details=Object.fromEntries(dailyBlogSep10Posts.map(p=>[p.slug,p.details]));
