type Topic={slug:string;title:string;excerpt:string;problem:string;artifact:string;owner:string};
const topics:Topic[]=[
['daily-article-intake-window','Set a daily article intake window','Turn requests into a workable queue with a cutoff and required fields.','Late requests displace reviewed drafts.','intake record naming audience, question, evidence, requester, risk, due time, and acceptance','editorial owner'],
['article-definition-of-ready','Use a definition of ready before drafting','Check the angle, sources, approvals, links, and image before work begins.','Writers start from titles that conceal missing evidence.','ready checklist for intent, scope, sources, prohibited claims, links, image, reviewer, and deadline','commissioning editor'],
['editorial-work-in-progress-limit','Limit work in progress in an offshore editorial queue','Protect finishing by limiting simultaneous briefs, drafts, reviews, and corrections.','Every article starts while few reach careful review.','lane board showing stage, owner, entered time, blocker, next action, and lane limit','content operations owner'],
['source-access-fallback','Plan source-access fallbacks for offshore research','Keep work moving when a source is blocked, paywalled, or unstable.','Access failures encourage second-hand claims.','source log linking each claim to access status, approved substitute, limitation, and reviewer','research editor'],
['article-review-timebox','Timebox article review without rubber-stamping','Reserve a review window and route unresolved risk before publication.','End-of-day review has no shared acceptance rule.','review sheet for claims, usefulness, duplication, links, image, metadata, decision, and risk','named publisher'],
['content-correction-log','Keep an article correction log','Record factual, link, metadata, and layout corrections with verification evidence.','Silent edits hide recurring causes.','correction log with URL, issue, impact, truth source, change, approver, SHA, and check time','accountable editor'],
['internal-link-review','Review internal links for reader usefulness','Verify destinations and anchors instead of linking to satisfy a count.','Irrelevant links interrupt the reader journey.','link record with source section, intent, destination, anchor, response, and decision','article editor'],
['content-handoff-cutoff','Design a clean daily publishing cutoff','Separate release candidates from work needing another evidence cycle.','Editing continues into deployment and mixes accepted work with drafts.','cutoff register with URL, content state, approvals, build state, owner, and carry-forward reason','release owner'],
['article-duplicate-angle-check','Check for duplicate article angles before drafting','Compare the question, decision, evidence, and promised outcome—not titles alone.','A new title can mask an existing article.','angle comparison naming nearest pages, overlap, new evidence, distinct decision, and disposition','content strategist'],
['editorial-exception-owner','Name an owner for editorial exceptions','Route unsupported claims, sensitive examples, and release conflicts correctly.','Contributors know when to stop but not who can decide.','exception map with trigger, evidence, primary owner, backup, target, and hold rule','subject owner'],
['post-publish-spot-check','Run a post-publish article spot check','Verify the live URL, date, canonical, schema, image, links, and mobile layout.','A successful deployment does not prove every route renders correctly.','live-check record with HTTP result, visible date, canonical, schema date, image, index, and sitemap','release owner'],
['article-carry-forward-rule','Use a carry-forward rule for unfinished articles','Move incomplete work with its evidence, blocker, owner, and next review intact.','Drafts reappear tomorrow without explaining why they missed today.','carry-forward note with stage, completed checks, blocker, owner action, new target, and expiry','queue owner']
].map(([slug,title,excerpt,problem,artifact,owner])=>({slug:`philippines-offshore-${slug}`,title:`${title} for a Philippines offshore content team`,excerpt,problem,artifact,owner})) as Topic[];
const headings=['Define the decision','Inspect one current item','Build the control record','Keep authority explicit','Test the normal path','Test an exception','Review operating evidence','Close the loop'];
const make=(t:Topic)=>({sections:headings.map((heading,i)=>({heading,paragraphs:[i===0?`Published September 4, 2026. ${t.problem} Frame the exact workflow stage and decision at risk before changing the routine.`:`Inspect an ordinary item and one late, incomplete, or sensitive item. Record what was known at the time, what the instructions allowed, and where work waited.`,`Maintain an ${t.artifact}. Link approved evidence rather than copying sensitive material, and leave unknown facts visibly unresolved.`,`The ${t.owner} makes the final decision. The offshore contributor prepares evidence, follows approved rules, and stops at the documented boundary. Review the result after one operating cycle.`]})),faqs:[{q:'Who owns the final decision?',a:`The ${t.owner} owns it; contributors prepare the record and escalate exceptions.`},{q:'What should be measured?',a:'Track waiting time, first-pass acceptance, repeat corrections, and exceptions resolved before the publishing cutoff.'}]});
export const dailyBlogSep4Posts=topics.map((t,i)=>({...t,minutes:8+i%3,publishedAt:'2026-09-04' as const,details:make(t)}));
export const dailyBlogSep4Details=Object.fromEntries(dailyBlogSep4Posts.map(p=>[p.slug,p.details]));
