type Topic={slug:string;title:string;excerpt:string;problem:string;record:string;limit:string;pilot:string};
const image='/images/daily-2026-08-21-source-repair-2/offshore-resourcing-article-release-checkpoint.webp';
const topics:Topic[]=[
['offshore-daily-content-standup-agenda','A 15-minute standup for an offshore daily content team','Use a short, evidence-led check-in to unblock research, drafting, review, and release work without turning the morning into a status meeting.','work waiting with no named decision or next check','a board view showing article, stage, blocker, owner, evidence link, and promised handoff','The standup surfaces decisions; it does not replace editorial approval or detailed review.','Run it for five workdays and compare blocker age and missed handoffs.'],
['philippines-article-brief-ready-check','How to decide when an article brief is ready for a Philippines-based writer','A ready check prevents writers from inheriting unresolved audience, scope, evidence, and approval decisions.','briefs containing a topic but no reader decision or evidence standard','a ready record with audience, question, exclusions, claims, source threshold, reviewer, and due time','The writer may flag gaps and suggest questions but should not silently define commercial or regulated claims.','Sample three briefs before assignment and record every clarification requested later.'],
['offshore-editorial-deep-work-blocks','Protect deep-work blocks in an offshore editorial schedule','Design focus windows around handoffs and review coverage so writers can concentrate without making queues invisible.','constant chat interruptions fragmenting research and drafting','a daily schedule naming focus blocks, response windows, emergency criteria, backup owner, and cutoff','Focus time does not suspend genuine incident escalation or agreed service commitments.','Test two focus blocks for a week and track interruptions, cycle time, and correction volume.'],
['offshore-content-definition-of-done','Write a definition of done for offshore content production','A shared finish line helps researchers, writers, reviewers, and publishers distinguish completed work from work merely passed onward.','articles marked complete before sources, metadata, links, or approval are verified','a checklist covering brief fit, claim support, originality, links, metadata, accessibility, approval, and live proof','Contributors attest to their own checks; only the authorized owner approves publication.','Apply the checklist to one ordinary article and one higher-risk article, then remove ambiguous items.'],
['philippines-writer-feedback-loop','Build a useful feedback loop for Philippines-based writers','Turn review comments into specific, repeatable guidance while keeping changes to the brief separate from writing defects.','the same correction returning because feedback describes taste rather than an acceptance rule','a feedback note with excerpt, issue class, expected rule, example, owner, and follow-up date','Feedback must not become unsupported performance scoring or a substitute for a clear brief.','Review ten comments, classify their cause, and test whether another editor interprets them consistently.'],
['offshore-publishing-cutoff-routine','Set a calm daily publishing cutoff for an offshore content operation','Use a release cutoff with explicit exceptions so late approvals do not create rushed metadata, image, or route checks.','articles entering release after reviewers no longer have time for all gates','a cutoff record with candidate routes, approval state, checks, exception owner, and carry-forward decision','Only the release owner accepts an exception; schedule pressure does not waive evidence or security checks.','Compare one week of releases against late changes, failed checks, and next-day corrections.'],
['offshore-content-correction-log','Keep a correction log for daily offshore article publishing','A lightweight log connects live fixes to their causes without encouraging quiet edits or blame.','corrections made with no record of affected claim, reader impact, or verification','an entry with URL, discovered time, old and new state, source, impact, approver, SHA, and recheck','The log documents and routes decisions; it does not authorize deleting history or changing unrelated pages.','Log the next five corrections and review whether each cause can be acted on.'],
['philippines-content-research-stop-rule','Give content researchers a defensible stop rule','Define what sufficient evidence looks like so a Philippines-based researcher can stop searching, expose gaps, and hand off a traceable record.','open-ended searching continuing after credible sources answer the bounded question','a source matrix with claim, source type, recency, corroboration, conflict, gap, and decision owner','The researcher reports uncertainty; the editor decides whether evidence supports publication.','Use the rule on two questions with different risk and note why search stopped.'],
['offshore-article-queue-aging-review','Review aging articles before they become silent backlog','Use age bands and reason codes to distinguish useful waiting from abandoned work in a daily content queue.','old drafts remaining assigned despite missing inputs or changed priorities','a weekly aging view with stage age, total age, waiting reason, owner, next action, and expiry decision','Coordinators can surface and recommend; the content owner reprioritizes, cancels, or changes scope.','Inspect the ten oldest items and resolve only those with clear authority and evidence.'],
['offshore-content-template-change-control','Control template changes across an offshore publishing team','Treat layout and metadata changes as releases with owners, examples, and rollback evidence rather than informal editing preferences.','a shared template changing while articles are already in review','a change note with purpose, affected routes, sample render, accessibility check, approver, SHA, and rollback trigger','Writers should not retrofit unapproved template changes or alter application code outside their role.','Trial the change on a representative route and compare desktop, mobile, metadata, and structured data.'],
['philippines-editorial-overlap-hours','Use overlap hours for decisions, not routine status updates','Reserve the shared window between Philippines and onshore teams for questions that require authority, judgment, or synchronous context.','overlap time consumed by updates already visible on the board','an overlap agenda listing decision, evidence, options, owner, deadline, and asynchronous context','Attendance does not transfer decision rights; sensitive or specialist matters remain with their named owners.','Audit one week of overlap topics and move informational updates to the shared record.'],
['offshore-content-weekly-retrospective','Run a weekly retrospective for a daily offshore content routine','Review flow and quality evidence together so the team improves the system without rewarding rushed article counts.','retrospectives relying on memory, anecdotes, or raw output totals','a one-page review of commitments, accepted articles, waits, rework, corrections, exceptions, and one experiment','The meeting improves process; it is not a venue for public individual ranking or unverified blame.','Choose one reversible change, name its measure and owner, and review it the following week.']
].map(([slug,title,excerpt,problem,record,limit,pilot])=>({slug,title,excerpt,problem,record,limit,pilot})) as Topic[];
const make=(t:Topic)=>({sections:[
{heading:'Name the operating problem',paragraphs:[`Published September 8, 2026. Start with ${t.problem}. Record one recent example and the consequence for a reader, reviewer, or release decision.`,`${t.excerpt} A narrow problem statement makes the routine testable and keeps the team from adding ceremony without purpose.`]},
{heading:'Create the minimum useful record',paragraphs:[`Use ${t.record}. Keep it in the system where the team already manages article work, and link evidence rather than copying sensitive material into a new tracker.`,`A useful record lets the next owner understand the current state, repeat the relevant check, and see when the item requires attention.`]},
{heading:'Define ownership and limits',paragraphs:[t.limit,`Write the escalation point beside the normal step. Missing evidence, disputed facts, personal data, security concerns, and policy interpretation require the appropriate accountable owner.`]},
{heading:'Fit it into the daily rhythm',paragraphs:[`Place routine review near the handoff it supports. Check new work before assignment, exceptions during overlap, and release evidence before the publishing cutoff.`,`Use asynchronous notes for normal progress. Reserve calls for choices that genuinely benefit from shared context or immediate authority.`]},
{heading:'Run a bounded pilot',paragraphs:[t.pilot,`Keep the acceptance standard stable during the pilot. Measure waiting time, first-pass acceptance, repeat questions, corrections, and unresolved exceptions instead of article count alone.`]},
{heading:'Adopt only what improves the work',paragraphs:[`Review the evidence with the people who research, write, edit, and release. Separate brief defects, access delays, review capacity, and execution errors before choosing a remedy.`,`Keep the routine when it clarifies ownership and produces more reliable evidence. Revise or remove any field that no one uses to make or verify a decision.`]}
],faqs:[{q:'Who should own this routine?',a:'The content manager owns the standard and decision rights; contributors maintain the records for the work they perform.'},{q:'What should the first pilot measure?',a:'Measure stage waiting, first-pass acceptance, repeated questions, live corrections, and unresolved exceptions while holding quality gates constant.'}]});
export const dailyBlogSep8Posts=topics.map((t,i)=>({...t,minutes:8+i%3,publishedAt:'2026-09-08' as const,image,details:make(t)}));
export const dailyBlogSep8Details=Object.fromEntries(dailyBlogSep8Posts.map(p=>[p.slug,p.details]));
