type Topic={slug:string;title:string;excerpt:string;decision:string;artifact:string;failure:string;pilot:string};
const image='/images/daily-2026-08-21-source-repair-2/offshore-resourcing-article-release-checkpoint.webp';
const topics:Topic[]=[
['offshore-content-morning-intake-window','The morning intake window that keeps an offshore content day predictable','A fixed intake window gives writers a stable queue without hiding urgent exceptions.','which briefs are genuinely ready before the writing day begins','an intake note with audience, reader question, source status, owner, due time, and exception flag','letting a late topic silently displace reviewed work','Compare planned and unplanned starts for five publishing days.'],
['philippines-writer-source-packet','Build a source packet a Philippines-based writer can actually use','Turn approved evidence into a compact map of claims, links, dates, and open questions.','which statements have enough support to draft responsibly','a claim-by-claim packet naming the source, relevant passage, publication date, and limitation','treating a long bookmark list as completed research','Test the packet on one factual guide and count clarification loops.'],
['offshore-blog-angle-collision-check','Catch overlapping blog angles before two drafts collide','A short collision check protects distinct search intent and prevents near-duplicate articles.','whether a proposed article answers a meaningfully different reader question','a comparison of target reader, decision, promise, outline, and closest existing routes','changing only the title while repeating an existing article identity','Review the next ten ideas against the index before approving briefs.'],
['content-review-comments-that-travel-across-time-zones','Write review comments that survive the time-zone handoff','Specific comments let an offshore writer revise without waiting for a second explanation.','what is wrong, why it matters, and what acceptable revision looks like','a comment with quoted text, issue type, requested outcome, evidence link, and decision owner','using vague directions such as make it stronger or improve the tone','Sample one revision round and track comments that required live follow-up.'],
['offshore-editorial-buffer-capacity','How much editorial buffer does a daily offshore publishing queue need?','Plan a small capacity reserve for source failures, revisions, and approval delays.','how much work can be promised without making quality depend on a perfect day','a weekly capacity view separating draft, review, approval, release, and contingency hours','filling every available hour with first-draft commitments','Reserve one modest buffer block for a week and record what actually consumes it.'],
['philippines-content-writer-example-library','Create an example library without teaching writers to copy','Annotated examples can clarify standards while preserving original thinking and route identity.','which qualities should repeat and which content must remain original','an example card naming the useful pattern, context, date, weaknesses, and reuse boundary','offering finished articles with no explanation of what the example teaches','Give two writers the same annotated example and compare interpretation.'],
['offshore-article-approval-expiry-rule','Give article approvals an expiry rule','A dated approval prevents an old brief or factual review from drifting into publication unchanged.','when changed evidence, scope, or timing requires another check','an approval record with scope, approver, date, dependencies, expiry trigger, and recheck owner','assuming approval remains valid after material claims or publication timing changes','Apply the rule to three queued articles with different evidence volatility.'],
['daily-content-queue-wip-limit','Set a work-in-progress limit for a daily content queue','A visible WIP limit exposes overloaded review stages before unfinished articles multiply.','how many items each stage can carry while owners still provide timely review','a board rule for research, drafting, editing, approval, and release with an exception owner','using the limit as a productivity target or hiding blocked items elsewhere','Start with observed throughput, test for one week, then adjust one stage.'],
['offshore-content-handoff-receipt','Use a handoff receipt for offshore article work','A short receipt confirms that the next owner has the files, context, and decision needed to proceed.','whether responsibility has truly transferred rather than merely been mentioned in chat','a receipt listing article state, evidence links, open questions, next action, owner, and promised check','marking work handed off before the receiver can access or understand it','Use receipts on five cross-time-zone handoffs and measure returned items.'],
['philippines-editor-first-pass-boundary','Define the first-pass boundary for a Philippines-based editor','Separate corrections an editor can make directly from changes that require subject or commercial approval.','which edits preserve the approved promise and which alter business meaning','an edit matrix covering mechanics, clarity, factual claims, examples, offers, policy, and escalation','letting deadline pressure turn editorial cleanup into unapproved strategy','Classify every change in one article revision and review disputed categories.'],
['offshore-blog-release-candidate-list','Build a release-candidate list before the publishing cutoff','Choose release candidates from verified readiness, not from whichever draft arrived last.','which articles can safely complete every remaining gate today','a candidate list showing approval, metadata, links, image, route, build, and fallback status','adding an unverified draft late merely to protect a volume target','Run the list at midday and again at cutoff for one publishing week.'],
['daily-article-routine-health-check','A Friday health check for a daily article routine','Use one week of queue evidence to select a small improvement without rewarding filler.','where the routine lost clarity, time, or verification during the week','a one-page view of starts, accepted drafts, waits, rework, corrections, and unresolved decisions','ranking contributors from raw article counts or drawing conclusions from anecdotes','Choose one reversible change and define the evidence to inspect next Friday.']
].map(([slug,title,excerpt,decision,artifact,failure,pilot])=>({slug,title,excerpt,decision,artifact,failure,pilot})) as Topic[];
const make=(t:Topic)=>({sections:[
{heading:'Start with the decision',paragraphs:[`Published September 9, 2026. The practical question is ${t.decision}. Write that question into the brief before adding fields or meetings.`,`${t.excerpt} The routine earns its place only when it helps an owner make or verify a real publishing decision.`]},
{heading:'Leave a record the next person can use',paragraphs:[`Create ${t.artifact}. Put it beside the article rather than in a private message, and link to source material instead of duplicating sensitive records.`,`The record should distinguish confirmed facts, editorial recommendations, unanswered questions, and decisions reserved for the accountable manager.`]},
{heading:'Protect the failure boundary',paragraphs:[`The main failure to prevent is ${t.failure}. Name a stop condition so a contributor can pause safely instead of guessing under deadline pressure.`,`Writers and coordinators may prepare, check, and recommend. Final publication, policy interpretation, sensitive claims, and commercial commitments remain with their authorised owners.`]},
{heading:'Fit the control into the day',paragraphs:[`Place the check immediately before the handoff it protects. Keep ordinary progress asynchronous, use overlap time for unresolved decisions, and preserve a dated result.`,`If the input changes after review, reopen only the affected gate. Do not force the whole article through ceremonial reapproval when the evidence shows a narrower recheck is enough.`]},
{heading:'Test it on live-shaped work',paragraphs:[t.pilot,`Use representative articles, including one normal item and one exception. Record waiting time, returned work, missed evidence, and the reason for any override.`]},
{heading:'Keep, revise, or remove it',paragraphs:[`At the end of the pilot, ask whether the control reduced ambiguity for the next owner. A field nobody uses to decide or verify something should be simplified or removed.`,`Adopt the routine only with a named owner and review date. Daily article creation improves through small observable corrections, not by accumulating permanent ceremony.`]}
],faqs:[{q:'Who owns this part of the routine?',a:'The content manager owns the standard; each contributor records the evidence for work they perform, and the authorised publisher owns release.'},{q:'What should the pilot measure?',a:'Measure waiting, returned work, missing evidence, live corrections, and unresolved decisions while keeping the quality standard stable.'}]});
export const dailyBlogSep9Posts=topics.map((t,i)=>({...t,minutes:8+i%3,publishedAt:'2026-09-09' as const,image,details:make(t)}));
export const dailyBlogSep9Details=Object.fromEntries(dailyBlogSep9Posts.map(p=>[p.slug,p.details]));
