type Topic={slug:string;title:string;excerpt:string;signal:string;record:string;boundary:string;trial:string};
const topics:Topic[]=[
['philippines-offshore-editorial-shift-handoff','How to run an editorial shift handoff across Philippines and onshore teams','A compact handoff keeps drafts, evidence questions, and publishing decisions from disappearing between workdays.','items that change owner without a next action','a handoff note with article, stage, evidence gap, decision owner, due time, and next check','The receiving editor may advance accepted work but may not infer approval from silence.','Test the note on one routine draft and one article held for a disputed source.'],
['philippines-offshore-content-sla-design','Set realistic content service levels for an offshore publishing team','Design response targets around risk and review capacity rather than promising that every request ships the same day.','requests that meet a clock but miss the reader need','a service-level table by request class, review depth, response target, and exception owner','The content lead sets priorities; coordinators do not downgrade evidence checks to rescue a deadline.','Compare promised and actual response times for two weeks before changing targets.'],
['philippines-offshore-brief-change-log','Keep brief changes visible during offshore article production','A brief-change log prevents late stakeholder edits from looking like writer rework or silent scope creep.','drafts revised against instructions that no longer match the original brief','a dated change record naming requester, reason, affected claims, schedule impact, and approver','Writers can flag impact and propose wording, while the commissioning editor accepts scope changes.','Follow one changed brief from request through final acceptance and note each waiting period.'],
['philippines-offshore-editorial-capacity-forecast','Forecast review capacity before assigning an offshore article batch','Plan around editing and verification hours so a full writing queue does not become a stranded review queue.','draft volume that exceeds the reviewers available before cutoff','a capacity view with article class, estimated review effort, named reviewer, buffer, and carry-forward rule','The release owner decides the batch; contributors report effort without self-approving publication.','Estimate one batch, record actual review time, and recalibrate by article class.'],
['philippines-offshore-source-verification-queue','Build a source-verification queue for offshore researchers','Separate source access, claim support, and editorial judgment so evidence questions reach the right owner quickly.','citations collected without showing which exact claim they support','a verification queue with claim, primary source, access date, excerpt location, limitation, and decision status','Researchers document what a source says but do not turn ambiguity into a stronger claim.','Sample five claims, including one with conflicting sources, and measure time to decision.'],
['philippines-offshore-article-acceptance-sampling','Sample accepted articles without re-reviewing every line','A risk-based sample can reveal recurring defects while keeping daily publishing work manageable.','quality checks that cover only easy articles or only known problem writers','a sampling plan stratified by topic risk, author, reviewer, format, and correction history','The quality owner selects and interprets the sample; production staff must not exclude inconvenient items.','Run the plan for one month and compare sampled defects with live correction reports.'],
['philippines-offshore-content-incident-triage','Triage live content incidents with an offshore support lane','Give broken links, wrong dates, missing images, and disputed claims distinct response paths and owners.','all production problems labeled urgent without considering reader harm','an incident card with affected URL, symptom, impact, evidence, safe containment, owner, and verification','The support lane may diagnose and prepare a patch; authorized publishers approve production changes.','Rehearse one broken asset and one factual concern using non-sensitive examples.'],
['philippines-offshore-editorial-dependency-map','Map dependencies before an offshore article enters production','A dependency map exposes approvals, assets, subject input, and technical checks that can delay an otherwise ready draft.','deadlines set before external inputs have owners or due times','a dependency list with provider, required input, fallback, latest safe date, and escalation path','Coordinators chase agreed inputs but cannot substitute unapproved assets or subject-matter conclusions.','Map three upcoming articles and review which dependency actually determines the release date.'],
['philippines-offshore-content-reuse-review','Review content reuse without creating near-duplicate articles','Treat existing pages as evidence and context, then define the genuinely new reader decision before drafting.','old copy repackaged under a fresh title and slug','a reuse review comparing intent, audience, claims, examples, links, and proposed new value','The strategist decides consolidation or creation; writers should not publish a second answer to the same question.','Compare the proposed article with its three closest search and site matches.'],
['philippines-offshore-publishing-rollback-plan','Prepare a safe rollback plan for daily article releases','Record how to withdraw a faulty release without losing the corrected source or disturbing unrelated pages.','teams improvising under pressure after a bad metadata or rendering change','a release note with SHA, routes, expected checks, rollback owner, trigger, and recovery verification','Only the authorized release owner initiates rollback; contributors preserve evidence and avoid unrelated edits.','Practice the decision path against a fictional failed image deployment.'],
['philippines-offshore-editorial-metrics-review','Choose editorial metrics that do not reward rushed offshore work','Pair speed with acceptance, correction, waiting, and evidence signals so the dashboard reflects publishable outcomes.','output counts encouraging shallow drafts and hidden corrections','a metric sheet defining numerator, denominator, source system, owner, caveat, and review cadence','Managers interpret performance; metrics must not become automatic personnel judgments without context.','Audit one month of data for missing denominators and changes in article mix.'],
['philippines-offshore-article-retirement-review','Review when an offshore resource article should be retired','Use reader intent, accuracy, links, traffic context, and replacement coverage to choose update, merge, redirect, or archive.','stale pages remaining live because nobody owns a retirement decision','a retirement brief with current claims, evidence age, inbound links, replacement page, risk, and approver','Researchers prepare the record; site owners approve redirects, removals, and canonical changes.','Pilot the review on one outdated low-risk page before handling high-value routes.']
].map(([slug,title,excerpt,signal,record,boundary,trial])=>({slug,title,excerpt,signal,record,boundary,trial})) as Topic[];
const make=(t:Topic)=>({sections:[
{heading:'Start with the operating failure',paragraphs:[`Published September 7, 2026. Look for ${t.signal}. Describe a real queue state, not a general concern, and name the reader or business decision affected.`,`${t.excerpt} The useful starting point is one observable failure and the record that should have made it visible.`]},
{heading:'Build the smallest useful record',paragraphs:[`Create ${t.record}. Keep source links in their approved systems and record only the context needed to repeat the check.`,`A complete entry should tell the next person what happened, what remains uncertain, and when the item becomes late.`]},
{heading:'Keep decision authority clear',paragraphs:[t.boundary,`Write the stop point beside the normal procedure. A contributor who reaches missing evidence, sensitive data, or an unapproved exception should pause and route the decision.`]},
{heading:'Fit the control into the daily routine',paragraphs:[`Review new exceptions near the start of overlap hours and aging items before the publishing cutoff. Close accepted entries with a URL or other verifiable output.`,`Avoid adding meetings when the shared record answers the question. Escalate only the cases that require authority, policy interpretation, or a tradeoff.`]},
{heading:'Run a bounded trial',paragraphs:[t.trial,`Measure elapsed time, first-pass acceptance, repeat questions, and unresolved exceptions. Preserve the same quality test during the trial so a faster result is not mistaken for a better one.`]},
{heading:'Review and improve',paragraphs:[`At the end of the trial, separate instruction gaps from access delays, capacity limits, and individual mistakes. Revise one control at a time and keep the earlier version available for comparison.`,`Adopt the routine only if it makes ownership and evidence easier to see without shifting prohibited decisions to the offshore contributor.`]}
],faqs:[{q:'Who owns the final decision?',a:'The named onshore or authorized content owner keeps approval authority; the offshore team prepares evidence and escalates exceptions.'},{q:'What should the first review measure?',a:'Check waiting time, first-pass acceptance, repeat corrections, unresolved exceptions, and whether every published output has verifiable evidence.'}]});
export const dailyBlogSep7Posts=topics.map((t,i)=>({...t,minutes:8+i%3,publishedAt:'2026-09-07' as const,details:make(t)}));
export const dailyBlogSep7Details=Object.fromEntries(dailyBlogSep7Posts.map(p=>[p.slug,p.details]));
