export type DailyBlog21 = { slug: string; title: string; excerpt: string; minutes: number; publishedAt: '2026-08-21'; image: string; details: { sections: { heading: string; paragraphs: string[] }[]; faqs: { q: string; a: string }[] } };

const entries = [
  ['offshore-resourcing-daily-article-intake', 'How to build a daily article intake lane for offshore resourcing', 'Turn article ideas into bounded briefs, evidence checks, and manager-ready decisions for a Philippines-based content support role.', 'article-intake.webp', ['Start with the reader decision', 'Capture the source request', 'Separate research from judgment', 'Set a useful brief size', 'Make missing context visible', 'Review the first handoff', 'Protect the publishing boundary', 'Refresh the intake lane']],
  ['offshore-resourcing-editorial-queue-ownership', 'Editorial queue ownership for a Philippines offshore support role', 'Design clear ownership for article requests, research notes, drafts, reviews, and unresolved questions without hiding manager decisions.', 'editorial-queue-ownership.webp', ['Name every queue state', 'Define the working owner', 'Use entry criteria', 'Record waiting reasons', 'Make review capacity visible', 'Route exceptions deliberately', 'Close the loop', 'Audit ownership drift']],
  ['offshore-resourcing-article-source-register', 'A source register for dependable offshore article support', 'Use a source register to keep claims, links, dates, and review decisions traceable while the accountable editor retains publication judgment.', 'article-source-register.webp', ['Give each claim an address', 'Record source fitness', 'Track freshness', 'Distinguish fact from advice', 'Handle conflicting evidence', 'Keep notes reusable', 'Escalate sensitive claims', 'Review the register']],
  ['offshore-resourcing-brief-to-draft-handoff', 'The brief-to-draft handoff for offshore content teams', 'Move from approved article brief to useful first draft with acceptance criteria, examples, and a clear route for ambiguity.', 'brief-to-draft-handoff.webp', ['Define draft readiness', 'Supply the working context', 'Set voice boundaries', 'Use an evidence packet', 'Mark uncertainty', 'Review structure before polish', 'Return actionable notes', 'Improve the handoff']],
  ['offshore-resourcing-content-review-sampling', 'Content review sampling for offshore article production', 'Sample drafts for claims, structure, relevance, and reader usefulness instead of treating publication volume as the only signal.', 'content-review-sampling.webp', ['Choose a representative sample', 'Score what matters', 'Separate defects from preferences', 'Check claim support', 'Look for role drift', 'Record reviewer time', 'Respond to patterns', 'Change one control']],
  ['offshore-resourcing-article-refresh-calendar', 'An article refresh calendar for offshore resourcing content', 'Plan refresh work around evidence age, reader decisions, and operational change rather than arbitrary calendar reminders.', 'article-refresh-calendar.webp', ['Map the change surface', 'Rank refresh triggers', 'Keep dates honest', 'Assign review ownership', 'Protect stable pages', 'Use a small update brief', 'Verify after editing', 'Learn from decay']],
  ['offshore-resourcing-content-exception-log', 'Why an offshore content team needs an exception log', 'Make blocked sources, disputed claims, late reviews, and unclear ownership visible so article work does not quietly become guesswork.', 'content-exception-log.webp', ['Define an exception', 'Write the minimum record', 'Assign the decision owner', 'Set a next check', 'Separate delay from defect', 'Prevent silent workarounds', 'Close with evidence', 'Review recurring causes']],
  ['offshore-resourcing-article-calendar-capacity', 'Capacity planning for a daily offshore article calendar', 'Match article commitments to research, writing, editing, and approval capacity so a daily routine remains credible and reviewable.', 'article-calendar-capacity.webp', ['Count the real stages', 'Model review bottlenecks', 'Reserve exception space', 'Set a sustainable queue', 'Use work-in-progress limits', 'Discuss trade-offs early', 'Measure completed quality', 'Adjust the plan']],
  ['offshore-resourcing-editorial-access-boundaries', 'Access boundaries for offshore article production', 'Give a Philippines-based content contributor the systems needed for repeatable work while keeping publishing, policy, and sensitive access with owners.', 'editorial-access-boundaries.webp', ['List the actual systems', 'Classify each permission', 'Separate draft from publish', 'Control downloads', 'Document temporary access', 'Review audit evidence', 'Revoke cleanly', 'Expand only by proof']],
  ['offshore-resourcing-article-performance-review', 'A useful performance review for offshore article support', 'Review article support through evidence quality, handoffs, rework, and reader fit instead of simplistic speed targets.', 'article-performance-review.webp', ['Start with agreed outcomes', 'Use observable evidence', 'Compare like work', 'Discuss rework fairly', 'Include written judgment', 'Keep coaching specific', 'Separate system issues', 'Set the next experiment']],
  ['offshore-resourcing-content-continuity-plan', 'Content continuity planning for offshore resourcing teams', 'Protect the daily article routine with current role notes, backup ownership, source records, and a safe absence handoff.', 'content-continuity-plan.webp', ['Identify fragile steps', 'Keep a current runbook', 'Name backup coverage', 'Protect source context', 'Test an absence handoff', 'Limit emergency access', 'Restore normal ownership', 'Review the plan']],
  ['offshore-resourcing-publishing-readiness-check', 'A publishing-readiness check for offshore article workflows', 'Use a final readiness check for dates, claims, links, role boundaries, and approval ownership before an article reaches the public site.', 'publishing-readiness-check.webp', ['Confirm the intended route', 'Check the article promise', 'Verify sources and dates', 'Inspect links and metadata', 'Test the role boundary', 'Confirm approval evidence', 'Record the release decision', 'Improve the checklist']],
] as const;

const lessons = [
  'A daily article lane begins with a decision the reader needs to make, not with a request for more words. The brief should say who the reader is, what operating problem they face, what evidence can inform the answer, and where the article must stop short of unsupported company claims. A Philippines-based support contributor can organize those inputs, but the accountable editor decides whether the public promise is accurate.',
  'The queue becomes manageable when each item has an entry condition, a current owner, and a next action. An article marked in progress is not useful evidence if nobody can tell whether research, drafting, review, or approval is waiting. Offshore resourcing works best when the record makes waiting visible and gives the next owner enough context to act without reconstructing a private conversation.',
  'A source register is more than a list of URLs. It should connect a claim to its source, the date checked, the reason the source is relevant, and any limitation that changes how the claim may be written. This lets a support role prepare careful research while the editor retains interpretation, risk judgment, and responsibility for what the audience sees.',
  'A good handoff transfers context, not just a file. The receiving owner should understand the article question, intended audience, accepted sources, unresolved points, and definition of a usable draft. If those details are absent, the next person spends time guessing. A bounded offshore role should surface the gap rather than smoothing it over with confident prose.',
  'Sampling should expose how the workflow behaves under ordinary and awkward conditions. Include a straightforward article, a thin source set, a conflicting source, a late review, and a topic that needs escalation. Reviewers can then distinguish a weak instruction from an individual mistake and improve the operating system instead of rewarding superficial throughput.',
  'Refresh work should follow meaningful change. A source may become stale, a service boundary may shift, a reader question may recur, or an article may no longer support the decision it names. A calendar is useful when it records why a page is due, who checks it, and what evidence will count as refreshed. It is not useful as a ritual that changes dates without changing truth.',
  'An exception log protects the queue from silent invention. Record what is blocked, why it matters, who can decide, and when the item will be checked again. That small discipline helps an offshore contributor pause safely and helps a manager see whether the same missing source, unclear brief, or access rule is creating repeated delay.',
  'Capacity is a property of the whole article path. Research, writing, editing, fact checking, image preparation, and approval each consume attention, and the narrowest stage controls the pace. A manager can use a simple work-in-progress limit to prevent a large pile of half-finished articles from hiding a review bottleneck or turning a daily commitment into rushed publishing.',
  'Access should follow the smallest useful permission. A contributor may need a brief repository, approved research sources, a draft workspace, and a review queue, while publishing, billing, account administration, and policy decisions stay with named owners. Documenting that boundary makes onboarding clearer and gives the manager something concrete to recertify when the role changes.',
  'Performance conversations are strongest when they discuss records, examples, corrections, and outcomes. Vague advice is difficult to act on; a specific instruction to flag an unsupported claim before review and link the missing evidence is observable. Offshore resourcing needs the same fairness as any other role: compare like work, separate instruction defects from execution defects, and agree on one next improvement.',
  'Continuity depends on written context that another person can use. Keep the queue definition, source register, access notes, approved examples, and escalation contacts current. A backup should be able to identify what is safe to finish, what must wait, and what needs the manager. Emergency coverage is not a reason to bypass the normal approval boundary.',
  'A final check should confirm that the article says what the brief approved, that its evidence supports its claims, that dates and links are truthful, and that the publication owner has actually approved release. The check is a decision record, not a ceremonial tick box. It gives a distributed team a shared stopping point before public content creates a new obligation.',
] as const;

const close = (topic: string, lesson: string, index: number) => `For ${topic.toLowerCase()}, the practical control is a dated record that another owner can inspect. ${lesson} Apply that principle to the article queue by naming the input, expected output, reviewer, unresolved question, and next check. The support role may prepare, organize, compare, and escalate. It should not invent facts about the company, approve a sensitive decision, publish without authorization, or turn a missing instruction into a promise. Managers can improve the lane by changing the smallest weak control, observing the next cycle, and keeping the reason for the change. A reliable offshore content routine is therefore a management system: useful work moves forward, uncertainty remains visible, and accountability stays with the person who can decide. This is especially important when daily article creation spans time zones, because written context must carry the work between handoffs. Review evidence such as corrections, waiting causes, source freshness, review time, and accepted drafts rather than using volume as a substitute for quality. (${index + 1})`;

export const dailyBlog21Posts = entries.map(([slug, title, excerpt, image, headings], index) => ({ slug, title, excerpt, minutes: 10 + (index % 2), publishedAt: '2026-08-21' as const, image: `/images/daily-2026-08-21/${image}`, details: { sections: headings.map((heading, sectionIndex) => ({ heading, paragraphs: [lessons[index], close(title, lessons[(index + sectionIndex + 1) % lessons.length], sectionIndex)] })), faqs: [{ q: `What should a manager check in ${title.toLowerCase()}?`, a: 'Check the work record, evidence behind the result, open exception, and named decision owner. Do not infer quality from speed alone.' }, { q: 'What should remain outside the support role?', a: 'Keep final approval, policy interpretation, sensitive exceptions, publishing authority, and access changes with the authorized owner.' }] } })) as DailyBlog21[];
export const dailyBlog21Details = Object.fromEntries(dailyBlog21Posts.map((post) => [post.slug, post.details]));
