export type DailyBlogSep2 = {
  slug: string;
  title: string;
  excerpt: string;
  minutes: number;
  publishedAt: '2026-09-02';
  details: { sections: { heading: string; paragraphs: string[] }[]; faqs: { q: string; a: string }[] };
};

type Topic = {
  slug: string;
  title: string;
  excerpt: string;
  problem: string;
  artifact: string;
  decision: string;
  measures: string[];
};

const topics: Topic[] = [
  { slug: 'philippines-offshore-first-30-days-scorecard', title: 'A first-30-days scorecard for a Philippines offshore hire', excerpt: 'Review readiness, supervised output, exceptions, and manager acceptance before increasing a new hire’s workload.', problem: 'A new team member can appear busy while still depending on private reminders and undocumented manager corrections.', artifact: 'a 30-day scorecard with workflow stage, expected evidence, sample size, exception count, review result, and next gate', decision: 'The hiring manager decides whether the evidence supports more volume, another supervised cycle, or narrower scope.', measures: ['accepted items by workflow', 'questions raised before action', 'review turnaround', 'repeat corrections'] },
  { slug: 'philippines-offshore-queue-priority-conflict-rule', title: 'Resolving priority conflicts in a Philippines offshore work queue', excerpt: 'Give offshore staff a safe rule for competing deadlines, urgent requests, and work owned by different managers.', problem: 'Two managers label their requests urgent, leaving the contributor to make an undeclared business tradeoff.', artifact: 'a priority-conflict record naming each request, consequence, due-time basis, current owner, proposed sequence, and escalation deadline', decision: 'The queue owner resolves conflicting commitments and records which work may move.', measures: ['conflicts resolved before cutoff', 'requests reordered by an authorised owner', 'late work with a recorded reason', 'repeat conflicts by source'] },
  { slug: 'philippines-offshore-access-request-evidence', title: 'Evidence required for Philippines offshore access requests', excerpt: 'Tie every requested permission to a named workflow, approved action, owner, duration, and removal trigger.', problem: 'Access is copied from a predecessor even though the new role handles fewer systems and decisions.', artifact: 'an access request listing workflow, system, permission level, approved actions, prohibited actions, owner, review date, and removal event', decision: 'The system owner approves the least access needed and rejects convenience-based inheritance.', measures: ['permissions linked to active work', 'requests returned for missing justification', 'access removed after scope changes', 'review findings by system'] },
  { slug: 'philippines-offshore-service-recovery-handoff', title: 'Designing a service-recovery handoff for Philippines offshore support', excerpt: 'Prepare facts, impact, options, and ownership when ordinary offshore support work creates a customer-facing problem.', problem: 'A routine processing error reaches a customer, but the internal handoff mixes diagnosis, apology, and approval authority.', artifact: 'a recovery handoff containing verified facts, affected commitment, containment taken, unanswered questions, authorised options, decision owner, and response deadline', decision: 'The customer owner approves external communication, remedy, and any changed commercial commitment.', measures: ['time to contain the issue', 'facts verified before escalation', 'decisions made before customer deadlines', 'guidance updated after closure'] },
  { slug: 'philippines-offshore-instruction-change-notice', title: 'Writing an instruction-change notice for Philippines offshore teams', excerpt: 'Move changed procedures into active work with an effective date, owner, examples, acknowledgement, and rollback rule.', problem: 'A manager edits a procedure while work is underway, and different shifts continue using different versions.', artifact: 'a change notice with reason, affected steps, effective time, old and new examples, approver, acknowledgement list, transition items, and rollback condition', decision: 'The process owner approves the change and decides how in-flight work will be treated.', measures: ['items completed under the correct version', 'acknowledgements before effective time', 'transition exceptions', 'rework caused by unclear changes'] },
  { slug: 'philippines-offshore-capacity-trigger-table', title: 'Building a capacity-trigger table for Philippines offshore operations', excerpt: 'Connect queue volume, age, complexity, and reviewer load to specific actions before service levels fail.', problem: 'The team watches a weekly average even as old exceptions and review-ready items accumulate.', artifact: 'a trigger table mapping each signal and threshold to an owner, immediate action, communication, recovery check, and reset condition', decision: 'Operations leaders approve workload deferral, coverage changes, and any revised commitment.', measures: ['oldest item by queue', 'review-ready backlog', 'exception share', 'time spent on rework'] },
  { slug: 'philippines-offshore-workflow-retirement-checklist', title: 'A workflow-retirement checklist for Philippines offshore roles', excerpt: 'Close obsolete work cleanly by removing access, archiving guidance, resolving open records, and notifying owners.', problem: 'A process stops, yet recurring tasks, permissions, and stale instructions remain attached to the role.', artifact: 'a retirement checklist covering final work, open exceptions, record location, access removal, automation dependencies, stakeholder notice, and accountable sign-off', decision: 'The process owner confirms the workflow is no longer required and accepts any residual obligations.', measures: ['open items closed or reassigned', 'permissions removed on time', 'obsolete schedules disabled', 'requests arriving after retirement'] },
  { slug: 'philippines-offshore-evidence-naming-standard', title: 'A naming standard for Philippines offshore work evidence', excerpt: 'Make files, screenshots, approvals, and queue records findable without exposing sensitive information in filenames.', problem: 'Review evidence is scattered under personal naming habits, making later acceptance and investigation slow.', artifact: 'a naming standard defining workflow code, record identifier, date, evidence type, version, sensitivity rule, and approved storage location', decision: 'The records owner approves naming and retention rules, especially where policy or personal data applies.', measures: ['evidence found from the queue record', 'duplicate files created', 'names exposing restricted data', 'versions used in final review'] },
  { slug: 'philippines-offshore-backlog-recovery-plan', title: 'Planning backlog recovery for a Philippines offshore support lane', excerpt: 'Reduce accumulated work with risk tiers, realistic throughput, protected review time, and explicit service tradeoffs.', problem: 'A team asks the offshore lane to catch up while normal intake continues unchanged and reviewers remain fully booked.', artifact: 'a recovery plan listing backlog age, risk tier, daily inflow, safe capacity, reviewer hours, deferred work, owner, and exit threshold', decision: 'The service owner chooses what to defer and approves any temporary change to coverage or commitments.', measures: ['net backlog change each day', 'oldest high-risk item', 'review capacity used', 'new defects during recovery'] },
  { slug: 'philippines-offshore-manager-absence-decision-cover', title: 'Decision coverage for a manager absence in Philippines offshore work', excerpt: 'Name backup authorities, limits, handoff records, and unavailable decisions before a manager is away.', problem: 'A backup can answer routine questions but cannot tell which approvals were delegated or which items must wait.', artifact: 'an absence decision map with decision type, primary owner, backup, authority limit, required evidence, contact window, and hold rule', decision: 'The primary manager and relevant policy owners confirm what can be delegated and what cannot.', measures: ['decisions completed by authorised backups', 'items held under the stated rule', 'unplanned contacts to the absent manager', 'handoff gaps found on return'] },
  { slug: 'philippines-offshore-output-acceptance-sampling', title: 'Sampling output acceptance in a Philippines offshore team', excerpt: 'Choose a representative review sample by risk, novelty, owner, and exception type instead of checking only easy work.', problem: 'Reported quality looks strong because reviewers sample ordinary completed items and overlook unusual cases.', artifact: 'a sampling plan specifying population, risk strata, period, sample size, selector, acceptance test, defect record, and follow-up action', decision: 'The accountable reviewer sets the sample and decides whether findings require broader inspection or instruction repair.', measures: ['acceptance by risk group', 'defects outside the routine sample', 'repeat issues after correction', 'review effort per accepted item'] },
  { slug: 'philippines-offshore-weekly-role-boundary-review', title: 'Running a weekly role-boundary review for Philippines offshore support', excerpt: 'Catch silent scope growth by reviewing new requests, decisions made, access used, exceptions, and rejected work.', problem: 'Small favors accumulate until the role handles work that was never reviewed for authority, training, or risk.', artifact: 'a boundary review log showing new request, requested action, current scope, access needed, decision owner, disposition, and documentation change', decision: 'The role owner approves, pilots, defers, or rejects each proposed expansion.', measures: ['out-of-scope requests', 'work stopped at a boundary', 'new access requested', 'scope changes supported by a pilot'] },
];

const headings = ['Define the operating question', 'Start from one recent work item', 'Create the shared control record', 'Separate preparation from authority', 'Test an ordinary case', 'Test an exception', 'Review the operating signals', 'Close with an owner decision'];

function sections(topic: Topic) {
  return headings.map((heading, index) => ({ heading, paragraphs: [
    index === 0 ? `Published September 2, 2026. ${topic.problem} The first review should identify the exact workflow, the expected finish, and the point where a manager decision becomes necessary.` : `${heading} should make ${topic.measures[index % topic.measures.length]} observable. Compare a normal item with one that arrived incomplete, late, or outside the usual path. Record what the contributor knew, what the instructions allowed, and what the next owner actually decided.`,
    `Use ${topic.artifact}. Keep the record beside the active queue and link to approved sources instead of copying sensitive data. A missing fact should remain visibly missing until an authorised owner supplies it; it should never be inferred merely to keep the queue moving.`,
    `${topic.decision} The offshore team member can prepare evidence, apply documented rules, and stop work at the stated boundary. After the next cycle, inspect ${topic.measures[(index + 1) % topic.measures.length]} and revise only the control that the evidence shows is weak.`,
  ] }));
}

export const dailyBlogSep2Posts: DailyBlogSep2[] = topics.map((topic, index) => ({
  slug: topic.slug, title: topic.title, excerpt: `${topic.excerpt} Published September 2, 2026.`, minutes: 9 + (index % 3), publishedAt: '2026-09-02',
  details: { sections: sections(topic), faqs: [
    { q: `Who owns the final decision for ${topic.title.toLowerCase()}?`, a: topic.decision },
    { q: 'What can the offshore team member do?', a: `The team member can prepare ${topic.artifact}, follow approved rules, and escalate missing authority or evidence.` },
  ] },
}));

export const dailyBlogSep2Details = Object.fromEntries(dailyBlogSep2Posts.map((post) => [post.slug, post.details]));
