import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,3);
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Role');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Clear scope, review rhythm, and measurable handoff.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));

export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="oys"><JsonLd data={schema}/>
<section className="oys-hero"><div className="oys-container"><p className="oys-kicker">Offshore hiring starts with the work</p><h1>Plan an offshore team around the work you need done.</h1><h2>Define the role, compare candidates, and set the checks before a new staff member gets access.</h2><div className="oys-actions"><a href="/contact">Request a role plan</a><a href="#map">See common roles</a></div></div><div className="oys-map" id="map"><div className="oys-globe"></div>{['Admin Assistant','Software Engineer','Data Analyst','Bookkeeper','Customer Rep','Operations Lead'].map((x,i)=><span className={`pin p${i}`} key={x}>your<br/><b>{x}</b></span>)}</div></section>
<section className="oys-container oys-care"><div><p className="oys-eyebrow">Before you hire</p><h2>Get the role clear before the resumes arrive.</h2><p>A useful staffing plan spells out the tasks, working hours, tool access, review process, and the decisions that stay with your team.</p></div><div className="oys-care-grid">{['One contact','Role guidance','Answers for your setup','Costs and limits'].map((x,i)=><article key={x}><span>{['●','✦','◆','✓'][i]}</span><h3>{x}</h3><p>{['Questions and follow-up go to one person.','The work you need covered shapes the role.','Your setup matters more than a canned job description.','Discuss costs and limits before hiring.'][i]}</p></article>)}</div></section>
<section className="oys-band"><div className="oys-container"><h2>Hire offshore staff without opening a local office.</h2><p>Start with a defined role. Then compare candidates, set up access, and check the first work before adding more.</p></div></section>
<section id="tasks" className="oys-container oys-roles"><h2>Choose the first work lane.</h2><div>{services.map((s:any,i:number)=><a href={`/services/${slug(s)}`} key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{title(s)}</h3><p>{text(s)}</p></a>)}</div></section>
<section className="oys-container oys-guides"><h2>Offshore hiring guides</h2>{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><b>{title(p)}</b><p>{text(p)}</p></a>)}</section>
<section className="oys-final"><div className="oys-container"><h2>Have a role in mind?</h2><a href="/contact">Request a role plan</a></div></section>
</main><Footer/></>}
