import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,3), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Role');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Clear scope, review rhythm, and measurable handoff.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));

export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="oys"><JsonLd data={schema}/>
<section className="oys-hero"><div className="oys-container"><p className="oys-kicker">The world is your talent bench</p><h1>Build offshore teams with people who care.</h1><h2>Managed resourcing for admin, support, finance, and tech roles across global talent markets.</h2><div className="oys-actions"><a href="/contact">Book a resourcing call</a><a href="#map">Get started</a></div></div><div className="oys-map" id="map"><div className="oys-globe"></div>{['Admin Assistant','Software Engineer','Data Analyst','Bookkeeper','Customer Rep','Operations Lead'].map((x,i)=><span className={`pin p${i}`} key={x}>your<br/><b>{x}</b></span>)}</div></section>
<section className="oys-container oys-care"><div><p className="oys-eyebrow">What makes this different</p><h2>The most human offshore resourcing desk.</h2><p>From the first role plan to sensitive quality moments, the right resourcing partner acts like an extension of your team — with empathy, accuracy, and local-market awareness.</p></div><div className="oys-care-grid">{['One point of contact','Expert guidance','Tailored answers','Support essentials'].map((x,i)=><article key={x}><span>{['●','✦','◆','✓'][i]}</span><h3>{x}</h3><p>{['who knows your business.','for high-stakes staffing choices.','shaped by your needs, not a script.','built in, not billed as surprises.'][i]}</p></article>)}</div></section>
<section className="oys-band"><div className="oys-container"><h2>Hire, onboard, and care for offshore staff without setting up local offices.</h2><p>Plan the role, shortlist candidates, manage onboarding, and keep a quality loop around every hire.</p></div></section>
<section className="oys-container oys-roles"><h2>Build the team you need now.</h2><div>{services.map((s:any,i:number)=><a href={`/services/${slug(s)}`} key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{title(s)}</h3><p>{text(s)}</p></a>)}</div></section>
<section className="oys-container oys-guides"><h2>Global resourcing guides</h2>{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><b>{title(p)}</b><p>{text(p)}</p></a>)}</section>
<section className="oys-final"><div className="oys-container"><h2>Ready to map your offshore team?</h2><a href="/contact">Request resourcing plan</a></div></section>
</main><Footer/></>}
