from pathlib import Path
import json

DATE = "2026-09-18"
topics = [
  dict(slug="philippines-talent-sourcing-search-plan", title="How to build a search plan for a Philippines talent sourcing specialist", excerpt="Turn a hiring request into a repeatable candidate search with explicit criteria, evidence, and manager review.", service="talent sourcing support", output="a search plan that names target titles, required evidence, exclusions, channels, and review checkpoints", risk="quietly widening the search or treating a keyword match as proof of fit", example="A software company needs a support analyst who can cover a defined customer window. The sourcer separates required troubleshooting experience from trainable product knowledge and records where each claim appears in the candidate profile.", link="/services/talent-sourcing-support"),
  dict(slug="candidate-screening-knockout-criteria-review", title="Review knockout criteria before offshore candidate screening begins", excerpt="Use a short review to keep screening criteria job-related, observable, and consistently applied.", service="candidate screening coordination", output="an approved screening sheet with criteria, evidence fields, permitted follow-up questions, and an exception owner", risk="rejecting a candidate from an assumption, inconsistent note, or unapproved proxy", example="A recruiting team requires written customer communication and four hours of overlap. The coordinator records evidence for both requirements and sends uncertain schedule answers to the hiring manager instead of guessing.", link="/services/candidate-screening-coordination"),
  dict(slug="philippines-interview-time-zone-confirmation", title="Prevent time-zone mistakes in Philippines interview scheduling", excerpt="Build a confirmation workflow that preserves the candidate's local time, the interviewer's time, and one source of truth.", service="interview scheduling", output="a calendar record containing the named time zones, converted times, attendees, meeting link, and confirmation status", risk="sending a plausible-looking time that was converted from an outdated message", example="A Manila candidate meets a manager in Chicago after a seasonal clock change. The coordinator checks the calendar's zone labels, sends both local times, and asks each party to confirm the same event record.", link="/services/interview-scheduling"),
  dict(slug="recruitment-administration-candidate-record-audit", title="Audit candidate records in a recruitment administration queue", excerpt="Check ownership, consent-sensitive fields, status evidence, and duplicate records before reporting pipeline numbers.", service="recruitment administration", output="a sampled audit record showing candidate ID, stage source, last verified action, duplicate check, and correction owner", risk="editing sensitive details without authority or presenting an inferred stage as confirmed", example="Two profiles share an email address after a referral import. The administrator links the possible duplicate, preserves the source records, and asks the system owner which record should remain authoritative.", link="/services/recruitment-administration"),
  dict(slug="workforce-planning-demand-assumption-log", title="Keep an assumption log for offshore workforce planning", excerpt="Separate measured workload from planning assumptions so managers can see what would change the staffing view.", service="workforce planning support", output="an assumption log with source period, workload unit, coverage rule, confidence note, owner, and review trigger", risk="turning an estimate into a headcount decision or hiding uncertainty behind a precise spreadsheet", example="A support queue rose during a product launch. The analyst shows observed ticket arrivals separately from the assumption that the launch pattern will continue, then models a range for manager review.", link="/services/workforce-planning-support"),
  dict(slug="philippines-onboarding-access-readiness-check", title="Run an access-readiness check before a Philippines-based hire starts", excerpt="Verify accounts, role-based permissions, owners, and fallback work without granting broad access early.", service="onboarding coordination", output="a readiness record listing each system, requested role, approver, provisioned status, test owner, and removal path", risk="sharing credentials, granting convenience access, or marking an untested account ready", example="A new recruitment coordinator needs the applicant tracker but not compensation reports. The onboarding owner provisions the limited role, tests a fictional record, and keeps restricted fields with the hiring manager.", link="/services/onboarding-coordination"),
  dict(slug="offshore-recruitment-sla-handoff-design", title="Design a useful handoff SLA for offshore recruitment support", excerpt="Set response expectations around candidate impact, decision ownership, and complete handoffs rather than raw speed.", service="recruitment operations support", output="a service table with queue event, required evidence, sender, receiver, response window, and escalation condition", risk="rewarding fast but incomplete handoffs or assigning decision deadlines to someone without authority", example="A candidate requests a schedule change after the normal overlap window. The coordinator logs the request and its consequence immediately; the hiring manager owns the decision by the next agreed review window.", link="/services/recruitment-administration"),
  dict(slug="candidate-source-consent-record-workflow", title="Create a candidate source and contact-permission record", excerpt="Give sourcers a consistent way to record where a profile came from and what outreach the approved workflow permits.", service="talent sourcing support", output="a source record with profile origin, access date, permitted use, prior contact check, outreach status, and retention owner", risk="copying unnecessary personal data or treating public visibility as unlimited permission", example="A sourcer finds a profile in an approved professional directory. The record links to the source, captures only job-relevant details, checks earlier contact, and uses the approved outreach channel.", link="/services/talent-sourcing-support"),
  dict(slug="interview-feedback-completeness-check", title="Check interview feedback before moving a candidate", excerpt="Make evidence and unresolved questions visible before an interview stage is closed or advanced.", service="interview scheduling and screening coordination", output="a feedback packet with criterion-level observations, interviewer identity, completion time, conflicts, and the decision owner", risk="averaging away disagreement or allowing the coordinator to make the hiring decision", example="One interviewer records strong troubleshooting evidence while another leaves the same criterion blank. The coordinator flags the missing evidence and holds the stage for the hiring manager rather than labeling the candidate inconsistent.", link="/services/candidate-screening-coordination"),
  dict(slug="offshore-recruiting-queue-priority-rules", title="Set priority rules for an offshore recruiting queue", excerpt="Order recruiting work by approved business need, candidate commitments, and blocking dependencies.", service="recruitment administration", output="a queue view with priority reason, due event, dependency, current owner, age, and next decision", risk="letting the newest message displace a documented candidate commitment or changing requisition priority without approval", example="An urgent hiring-manager request arrives while two candidates are waiting for promised interview details. The coordinator protects the candidate commitments and asks the priority owner where the new request belongs.", link="/services/recruitment-administration"),
  dict(slug="philippines-new-hire-first-week-evidence", title="Define first-week evidence for a Philippines-based new hire", excerpt="Replace vague ramp expectations with a small set of observable outputs, review points, and safe practice work.", service="onboarding coordination", output="a first-week plan naming practice tasks, accepted examples, system limits, reviewers, questions, and daily evidence", risk="measuring presence instead of learning or expanding live access before work is checked", example="A new sourcing specialist completes a fictional search, explains two exclusions, and corrects one record after review before receiving a limited live assignment.", link="/services/onboarding-coordination"),
  dict(slug="offshore-role-pilot-go-no-go-review", title="Run a go/no-go review after an offshore role pilot", excerpt="Use quality, handoff, workload, and access evidence to decide whether a role should expand, pause, or change.", service="workforce planning and onboarding support", output="a pilot decision brief with planned scope, completed samples, defects, waits, access exceptions, manager load, and next action", risk="declaring success from output volume alone or blaming the worker for a broken process", example="A two-week recruitment administration pilot meets its accuracy target but requires daily manager correction because intake fields are often missing. The manager continues the pilot with a repaired intake rather than expanding volume.", link="/services/workforce-planning-support"),
]

sources = [
  {"name":"Philippine National Privacy Commission — Data Privacy Act resources","url":"https://privacy.gov.ph/data-privacy-act/","note":"Primary Philippine guidance for handling personal information and accountability."},
  {"name":"NIST Privacy Framework","url":"https://www.nist.gov/privacy-framework","note":"A voluntary framework for identifying and managing privacy risk."},
  {"name":"CISA — Implementing Phishing-Resistant MFA","url":"https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa","note":"Current first-party security guidance relevant to workforce account access."},
]

def article(t):
  s=t["service"]
  return [
    ("Start with the buyer decision", [
      f"A company considering {s} does not only need another person to move tasks. It needs a dependable answer to a management question: can this work be prepared offshore while hiring authority, sensitive access, and exceptions remain with the right owner? Begin by naming the decision the routine supports, the evidence the manager expects, and the consequence of a missed handoff. That framing keeps the role tied to a real staffing choice instead of a generic promise of capacity.",
      f"The practical deliverable is {t['output']}. Write it before assigning live work. It gives a Philippines-based specialist a clear target and gives the receiving manager something concrete to inspect. A useful record distinguishes a confirmed fact, a contributor's observation, an open question, and a decision. Those labels matter because a neat record can still be misleading when assumptions are presented as facts."
    ]),
    ("Map the workflow before choosing tools", [
      f"Trace one ordinary item from arrival to closure. Name the source, required fields, checks, handoff, approval, and final system of record. Then trace one awkward item with missing information or conflicting instructions. The second path usually reveals where {t['risk']}. Put that stop condition in the workflow and name the person who can resolve it.",
      "Do not begin with software permissions. Begin with the work and its authority boundaries, then grant the smallest access that supports the approved steps. Shared credentials make attribution and removal harder. Separate accounts, role-based permissions, multifactor authentication, and a documented removal owner make the operating record easier to trust. Apply the client's legal, security, contractual, and retention requirements before any real candidate or employee data enters the lane."
    ]),
    ("Define inputs and acceptance evidence", [
      f"For every assigned item, list the minimum input and what acceptable completion looks like. In this workflow, completion should be demonstrated by {t['output']}. Avoid a status such as “done” when it does not show the source checked, the action taken, and the next owner. A receiver should be able to reproduce the important check without asking the contributor to reconstruct it from memory.",
      "Use accepted and rejected examples from the company's own workflow, with private data removed. Explain why each example passes or fails. Examples reveal details that a short policy often misses: how to record uncertainty, which field controls downstream reporting, and when a seemingly minor discrepancy must stop the queue. Keep the current example version beside the instruction so reviewers do not grade new work against an obsolete standard."
    ]),
    ("Work through a realistic example", [
      t["example"],
      "The lesson is not that every exception needs a meeting. It is that the routine must preserve enough context for the authorised owner to decide. The specialist can collect evidence, identify conflicts, prepare options, and maintain the record. The manager still owns the consequential choice. When the boundary is visible, escalation becomes a normal part of good work rather than a sign that the contributor failed."
    ]),
    ("Set privacy and access boundaries", [
      "Candidate and workforce records can contain contact details, employment history, interview notes, availability, and other personal information. Collect only what the approved purpose requires. Record where information came from, restrict exports, and define how corrections and deletion requests reach the responsible owner. The Philippine National Privacy Commission's Data Privacy Act materials are a primary starting point, while the client's applicable jurisdiction and contracts may impose additional duties.",
      "Run the workflow with fictional data before granting access to live records. Test whether the specialist can complete the expected output, whether restricted fields stay hidden, whether the audit trail identifies the user, and whether access can be removed promptly. A successful login is not an access-readiness test. The test should prove that the intended work is possible and an unintended action is blocked or escalated."
    ]),
    ("Choose service measures that expose quality", [
      "Measure a balanced set of signals: accepted work, returned work by reason, overdue handoffs, unresolved exceptions, record corrections, and manager review time. Segment results by work type so a batch of easy items does not hide difficult cases. Volume and speed can provide context, but neither proves that screening, scheduling, sourcing, or planning work was correct. Pair every throughput measure with an evidence-quality check.",
      "Set a temporary review cadence for the pilot. Inspect the first few items closely, then sample only after the team sees stable performance. Increase review again when the workflow, source system, reviewer, or role scope changes. Record why an item was returned in language that helps repair the instruction or output. Do not use operational notes as covert performance ratings or as a substitute for a fair management process."
    ]),
    ("Design the handoff and escalation path", [
      "A complete handoff says what arrived, what was checked, what changed, what remains unresolved, who acts next, and when a response is needed. Attach links to the system of record rather than copying sensitive details into chat. If the next owner does not acknowledge a consequential handoff, the item remains open. That rule prevents a sent message from being mistaken for accepted responsibility.",
      f"Write an escalation ladder for {s}. The first level covers missing routine inputs. The next covers conflicting evidence, access failures, or a candidate commitment at risk. The final level covers privacy, security, legal, financial, or policy concerns that the specialist must not resolve alone. Give each level a channel, response expectation, backup owner, and safe holding action."
    ]),
    ("Pilot the routine and decide what changes", [
      "Use a bounded pilot with ordinary work, an exception, and a deliberate missing input. Tell participants that the exercise tests the workflow as well as the contributor. Review the resulting records, not just the final status. Ask whether another authorised person could understand the evidence, continue the queue, and identify the decision owner. Correct unclear fields and permissions before adding more volume.",
      f"At the end, choose among expand, continue, narrow, repair, or stop. Document the reason and the next review date. If the lane is useful, connect it to Offshore Resourcing's {s} pathway and turn the proven task list into a role brief. The role plan should reflect your systems, hours, evidence requirements, and manager-owned decisions."
    ]),
  ]

def ts_str(x): return json.dumps(x, ensure_ascii=False)

rows=[]
for t in topics:
  sections=article(t)
  rows.append("  {\n" +
    f"    slug: {ts_str(t['slug'])}, title: {ts_str(t['title'])}, excerpt: {ts_str(t['excerpt'])}, minutes: 10, publishedAt: {ts_str(DATE)}, image,\n" +
    "    details: { sections: [\n" + ",\n".join(
      "      { heading: %s, paragraphs: [%s] }" % (ts_str(h), ", ".join(ts_str(p) for p in ps)) for h,ps in sections
    ) + "\n    ], sources, faqs: [\n" +
    f"      {{ q: {ts_str('What should the manager approve?')}, a: {ts_str('The manager approves the role scope, access, exceptions, and any hiring or workforce decision. The specialist prepares and records work inside those limits.')} }},\n" +
    f"      {{ q: {ts_str('How long should the pilot run?')}, a: {ts_str('Run enough ordinary and exception cases to review the handoff and evidence. Use a fixed review date rather than expanding automatically after a calendar interval.')} }}\n" +
    "    ] }\n  }")

out = """type Source={name:string;url:string;note:string};
type Section={heading:string;paragraphs:string[]};
type Post={slug:string;title:string;excerpt:string;minutes:number;publishedAt:string;image:string;details:{sections:Section[];sources:Source[];faqs:{q:string;a:string}[]}};
const image='/images/thumbnail-backgrounds/talent-map.webp';
const sources:Source[]=%s;
export const dailyBlogSep18Posts:Post[]=[
%s
];
export const dailyBlogSep18Details=Object.fromEntries(dailyBlogSep18Posts.map(p=>[p.slug,p.details]));
""" % (json.dumps(sources, ensure_ascii=False), ",\n".join(rows))

Path("app/daily-blog-2026-09-18.ts").write_text(out)
manifest={"family":"blog","required":12,"publicationDate":DATE,"timezone":"UTC","articles":[{"slug":t["slug"],"route":"/blog/"+t["slug"],"topic":t["title"],"sourcePaths":["app/daily-blog-2026-09-18.ts"],"sources":[s["url"] for s in sources]} for t in topics]}
Path(f".paperclip/daily-content/{DATE}").mkdir(parents=True, exist_ok=True)
Path(f".paperclip/daily-content/{DATE}/blog.json").write_text(json.dumps(manifest,indent=2)+"\n")
